### ISSUE TITLE
 Running the command pdf(55mb) will time out.

### ISSUE THREAD

**Issue by DTwz** [magicpdf/Magic-Doc#48]
Running the command python magic_doc/cli.py --file-path magic_doc/datas/test.pdf --output magic_doc/datas_new will time out.
magic_doc.docconv.ConvException: Convert timeout.
2024-06-21 18:08:50.926 | INFO     | __main__:cli_conv:103 - total cost time: 0 seconds
2024-06-21 18:08:50.926 | INFO     | __main__:cli_conv:104 - total convert error: 0
2024-06-21 18:08:50.926 | INFO     | __main__:cli_conv:105 - total file broken: 0
2024-06-21 18:08:50.926 | INFO     | __main__:cli_conv:106 - total unsupported files: 0
2024-06-21 18:08:50.926 | INFO     | __main__:cli_conv:107 - total time out: 1
2024-06-21 18:08:50.926 | INFO     | __main__:cli_conv:108 - total success: 0
^CException ignored in: <module 'threading' from '/home/PJLAB/wangzhou/anaconda3/envs/py310/lib/python3.10/threading.py'>
Traceback (most recent call last):
  File "/home/PJLAB/wangzhou/anaconda3/envs/py310/lib/python3.10/threading.py", line 1537, in _shutdown
    atexit_call()
  File "/home/PJLAB/wangzhou/anaconda3/envs/py310/lib/python3.10/concurrent/futures/thread.py", line 31, in _python_exit
    t.join()
  File "/home/PJLAB/wangzhou/anaconda3/envs/py310/lib/python3.10/threading.py", line 1096, in join
    self._wait_for_tstate_lock()
  File "/home/PJLAB/wangzhou/anaconda3/envs/py310/lib/python3.10/threading.py", line 1116, in _wait_for_tstate_lock
    if lock.acquire(block, timeout):

**Comment by icecraft** [comment]
try to increase the time-out param
